channels:
    - conda-forge
    - defaults

dependencies:
    - python
    - setuptools
    - pip
    - numpy
    - scipy
    - pyyaml
    - ruamel.yaml
    - pytest
    - pytest-benchmark
    - h5py
    - six
    - pandas
