package:
  name: exdir
  version: {{ environ.get("GIT_DESCRIBE", "unknown_version")|replace("v", "")|replace("-", "_") }}
  
source:
  path: .
 
build:
  script: python setup.py install

requirements:
  build:
    - python
    - setuptools
    - pip
    - numpy
    - quantities
    - pyyaml
    - versioneer
    - pytest

  run:
    - python
    - setuptools
    - pip
    - numpy
    - scipy
    - quantities
    - pyyaml

test:
  imports:
    - exdir
  commands:
    - python -c "import exdir; print(exdir.__version__)"

about:
  home: https://github.com/CINPLA/exdir/
  license: MIT
  license_file: LICENSE
