package:
  name: exdir
  version: {{ environ.get("GIT_TAG", "0.0.0_custom")|replace("v", "")|replace("-", "_") }}
  
source:
  git_url: ..
 
build:
  # noarch: python  # TODO Add back noarch when it works properly on Windows,
                    # we are converting packages manually now
  script: python setup.py install

requirements:
  build:
    - python
    - setuptools
    - pip
    - numpy
    - quantities
    - pyyaml
    - pytest
    - six

  run:
    - python
    - setuptools
    - pip
    - numpy
    - scipy
    - quantities
    - pyyaml
    - six

test:
  requires:
    - pytest
  source_files:
    - tests
  imports:
    - exdir
  commands:
    - python -c "import exdir; print(exdir.__version__)"
    - pytest -s

about:
  home: https://github.com/CINPLA/exdir/
  license: MIT
  license_file: LICENSE
