package:
  name: exdir
  version: {{ environ.get("GIT_TAG", "0.0.0_custom")|replace("v", "")|replace("-", "_") }}

source:
  git_url: ..

build:
  # noarch: python  # TODO Add back noarch when it works properly on Windows,
                    # we are converting packages manually now
  script:
    # TODO remove this and add back quantities as conda package once its updated with the new numpy API
    - pip install git+https://github.com/python-quantities/python-quantities.git
    - python setup.py install

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - setuptools
    - pip
    - numpy
    - scipy
    - pyyaml

test:
  requires:
    - pytest
    - pytest-benchmark
    - h5py
    - six
  source_files:
    - tests
  imports:
    - exdir
  commands:
    - python -c "import exdir; print(exdir.__version__)"
    - pytest -s

about:
  home: https://github.com/CINPLA/exdir/
  license: MIT
  license_file: LICENSE
