package:
  name: exdir
  version: {{ environ.get("GIT_TAG", "0.0.0_custom")|replace("v", "")|replace("-", "_") }}

source:
  git_url: ..

build:
  noarch: python
  script: python setup.py install

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - setuptools
    - numpy
    - scipy
    - ruamel_yaml
    - enum34  # for Python 2.7
    - six  # for Python 2.7

test:
  requires:
    - pytest
    - pytest-benchmark
    - h5py
    - six
    - coverage
    - codecov
    - sphinx
    - quantities

  source_files:
    - tests
    - docs
  imports:
    - exdir
  commands:
    - python -c "import exdir; print(exdir.__version__)"
    - coverage run --source tests -m py.test -s
    - coverage report
    - codecov
    - cd docs ; make doctest

about:
  home: https://github.com/CINPLA/exdir/
  license: MIT
  license_file: LICENSE
